-- drop table mail_inbox;

create table mail_inbox(
  id number
    generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20
    noorder nocycle nokeep noscale
    not null enable
  ,row_version number(*,0) not null enable
  ,created timestamp(6) with local time zone not null enable
  ,created_by varchar2(255 char) collate using_nls_comp not null enable
  ,updated timestamp(6) with local time zone not null enable
  ,updated_by varchar2(255 char) collate using_nls_comp not null enable
  ,security_group_id number not null enable
  ,mail_json clob collate using_nls_comp not null enable
  ,constraint mail_inbox_ck1 check ( mail_json is json ) enable
  ,constraint mail_inbox_pk primary key ( id ) enable
);

create or replace editionable trigger mail_inbox_biu
  before insert or update
  on mail_inbox
  for each row
begin
  if inserting then
    :new.row_version := 1;
    :new.created := localtimestamp;
    :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'), sys_context('USERENV','SESSION_USER'));
  elsif updating then
    :new.row_version := coalesce(:old.row_version,0) + 1;
  end if;

  if :new.security_group_id is null then
    :new.security_group_id := 0;
  end if;

  :new.updated := localtimestamp;
  :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'), sys_context('USERENV','SESSION_USER'));
end mail_inbox_biu;

/
alter trigger mail_inbox_biu enable;
